name: Unit test
permissions:
  contents: read
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          make install_tool && make update_idl
          sudo apt-get update && sudo apt-get install -y clang llvm libbpf-dev
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
          go generate biz/services/peer/mux_local/ban/xdp/filter.go
          go test ./...

